.TH URLSCAN 1 "November 10, 2014"

.SH NAME
urlscan \- browse the URLs in an email message from a terminal
.SH SYNOPSIS
\fBurlscan\fR [options] <
.I message

\fBurlscan\fR [options]
.I message

.SH DESCRIPTION
\fBurlscan\fR accepts a block of text on standard input, and outputs
a list of URLs parsed from that text, one URL per line.

\fBurlscan\fR is similar to \fBurlview\fR(1), but more closely follows
the UNIX philosophy in that it leaves the display of URLs up to other
programs.

.SH SEE ALSO
\fI/usr/share/doc/urlscan/README\fR,
\fBurlview\fR(1),

.SH AUTHOR
This manual page was written by Daniel Burrows <dburrows@debian.org> and Scott Hansen <firecat4153@gmail.com>
